# Анализ и прогнозирование неоднородных временных рядов, БИ

## НИУ ВШЭ, 2022-23 учебный год

### Домашнее задание №2. Библиотека Numpy

Задание выполнил(а): Иван Павлович

### Общая информация

__Дата выдачи:__ 09.11.2022

__Дедлайн:__ 04:00 20.11.2022

### Оценивание и штрафы

Каждая задача оценивается в 2 балла.

Оценка за ДЗ вычисляется по следующей формуле:

$$
s_{\text{numpy}} \times 1/2 ,
$$

где $s_{\text{numpy}}$  — количество баллов, которое вы набрали в сумме по задачам.

За сдачу задания позже срока на итоговую оценку за задание накладывается штраф в размере 1 балл в день, но  задержка не может быть больше недели.

__Внимание!__ Домашнее задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов.

### Формат сдачи

Будет объявлен ближе к дедлайну в канале

### О задании

В данном домашнем задании вы попрактикуетесь в работе с библиотекой numpy!

In [30]:
import numpy as np

Во всех задачах необходимо написать код решения внутри функции и проверить его работу, вызвав функцию для данных из условия.

При решении задач запрещается использовать циклы (`for`, `while`) и оператор `if`.

Везде, где встречаются массивы или матрицы, подразумевается, что это `numpy.array`. 

### 1

Напишите функцию, возвращающую округленную взвешенную сумму оценок по данным оценкам и весам. Можете посчитать свою оценку за курс :) В нашем случае вес экзамена равен 0.35, вес домашек - 0.4, вес проекта - 0.15, вес аудиторки - 0.1. Например, если экзамен написан на 6, домашки сданы на 9, проект закрыт на 8, а оценка за аудиторку 7 - итоговая оценка будет отлично - 8 

In [4]:
def result_mark(weights, marks):
     print(np.sum(weights * marks))

In [5]:
weights = np.array([0.35, 0.4, 0.15, 0.1])
marks = np.array([6, 9, 8, 7])
result_mark(weights, marks)

7.6


### 2

Напишите функцию, меняющую каждое третье (начиная с 0) значение массива целых чисел на заданное число. Например, если на вход поступает массив `array([3, 5, 1, 0, -3, 22, 213436])` и число `-111`, то на выходе должен получиться массив `array([-111, 5, 1, -111, -3, 22, -111])`.

In [41]:
def change_array(array, number):
    array[::3] = number
    print(array)
    
    #or
        #for i in range(0,len(array)):
            #if i % 3 == 0:
                #array[i] = number

        #print(array)

In [42]:
array = np.array([3, 5, 1, 0, -3, 22, 213436])
number = -111
change_array(array, number)

[-111    5    1 -111   -3   22 -111]


### 3

Напишите функцию, выдающую индексы «близких» элементов заданных массивов, а именно тех пар элементов, чей модуль разницы не превосходит заданного значения. Например, если на вход поступают массив `array([1.5, 0.5, 2, -4.1, -3, 6, -1])`, массив `array([1.2, 0.5, 1, -4, 3, 0, -1.2])` и число `0.5`, то на выходе должен получиться массив `array([0, 1, 3, 6])` (_**важно: не `tuple`, а одномерный массив типа `numpy.ndarray` (то есть `.ndim` от него равно 1)!**_).

In [83]:
def find_close(array1, array2, precision):
    c = np.arange(array1.size) # массив с индексами
    print(c[abs(array2-array1)<=precision]) 

array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4, 3, 0, -1.2])
precision = 0.5
find_close(array1, array2, precision)

### 4

Напишите функцию, которая составляет блочную матрицу из четырех блоков, где каждый блок - это заданная матрица. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
\end{pmatrix},
$$
то ответом будет матрица
$$
\begin{pmatrix}
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
0 & 1 & 2 & 0 & 1 & 2\\
3 & 4 & 5 & 3 & 4 & 5\\
\end{pmatrix}
$$

In [12]:
def block_matrix(block):
    block = np.concatenate([block,block],axis=1) #https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html
    block = np.concatenate([block, block], axis=0)
    print(block)

In [13]:
block = np.array([[0, 1, 2], [3, 4, 5]])
block_matrix(block)

[[0 1 2 3 0 1 2 3]
 [3 4 5 7 3 4 5 7]
 [0 1 2 3 0 1 2 3]
 [3 4 5 7 3 4 5 7]]


### 5

Напишите функцию, вычисляющую произведение всех ненулевых диагональных элементов на диагонали данной квадратной матрицы. Например, если на вход поступает матрица
$$
\begin{pmatrix}
0 & 1 & 2\\
3 & 4 & 5\\
6 & 7 & 8\\
\end{pmatrix},
$$
то ответом будет 32.

In [39]:
def diag_prod(matrix):
    
    d = np.diagonal(matrix)       #https://pyprog.pro/indexing_routines/diagonal.html
    print(np.delete(d,0).prod())     #https://pyprog.pro/array_manipulation/delete.html
    
#or
# i = 0
# j = 0
# (a,b) = np.shape(matrix)
# for i in range(a-1):
# for j in range(b-1):
# sum = matrix[i,j] * matrix[i+1,j+1]
# print(sum)

In [40]:
matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
diag_prod(matrix)

32


### 6

Для улучшения качества работы некоторых алгоритмов машинного обучения может быть полезно использовать [нормализацию данных](https://vk.cc/8xmfQk), чтобы привести признаки в выборке к одному масштабу — а именно, из каждого столбца вычесть среднее его значений и поделить на их стандартное отклонение. Напишите функцию, нормализующую входящую матрицу (по столбцам). Например, если на вход подается матрица 
$$
\begin{pmatrix}
1 & 4 & 4200\\
0 & 10 & 5000\\
1 & 2 & 1000\\
\end{pmatrix},
$$
то результатом с точностью до сотых будет матрица
$$
\begin{pmatrix}
0.71 & -0.39 & 0.46\\
-1.41 & 1.37 & 0.93\\
0.71 & -0.98 & -1.39\\
\end{pmatrix}
$$

_Подсказка. Учтите, что в вашей матрице не должно получаться никаких nan. Подумайте, в каком случае они могут возникнуть и как обойти эту проблему._


In [86]:
def normalize(matrix):
    av = np.mean(matrix, axis=0)  # среднне для столбцов https://pyprog.pro/statistics_functions/mean.html
    dd = np.std(matrix,axis=0)  # среднее отклонение для столбцов https://tonais.ru/library/funktsiya-numpy-std-v-python\


    # axis=0 для столцов!!! axis=1 для строк (полчаса искал ошибку)

    dd[dd == 0] = np.mean(dd)

    # отколенение может быть нулевым => нужно расмотреть случай деления на ноль, и я не понял, как именно
    # некоторые чуваки просто ставели в ответ ноль или делили на 1, но мне кажется резонно просто взять среднее отклонение
    # это будет достоверней деления на 1 или просто нуля в ответе

    print(np.around(np.divide(matrix - av, dd), decimals=2))

In [85]:
matrix = np.array([[1, 4, 4200], [0, 10, 5000], [1, 2, 1000]])
normalize(matrix)

[[ 0.71 -0.39  0.46]
 [-1.41  1.37  0.93]
 [ 0.71 -0.98 -1.39]]


### 7

Напишите функцию, вычисляющую какую-нибудь первообразную данного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному $4x^3 + 6x^2 + 1$, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному $x^4 + 2x^3 + x - 2$.

In [16]:
def antiderivative(coefs):
    print(np.polyint(coefs))  #https://runebook.dev/ru/docs/numpy/reference/generated/numpy.polyint

In [17]:
coefs = np.array([4, 6, 0, 1])
antiderivative(coefs)

[1. 2. 0. 1. 0.]


### 8

Напишите функцию, делающую данную [треугольную матрицу](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86%D0%B0) симметричной. Например, если на вход поступает матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
0 & 5 & 6 & 7\\
0 & 0 & 8 & 9\\
0 & 0 & 0 & 10\\
\end{pmatrix},
$$
то на выходе должна быть матрица
$$
\begin{pmatrix}
1 & 2 & 3 & 4\\
2 & 5 & 6 & 7\\
3 & 6 & 8 & 9\\
4 & 7 & 9 & 10\\
\end{pmatrix}.
$$

In [51]:
def make_symmetric(matrix):
    switched = np.array(tuple(zip(*np.flip(matrix,axis=0 )[::-1]))) 
   
   # https://numpy.org/doc/stable/reference/generated/numpy.flip.html
   #https://ru.stackoverflow.com/questions/605620/Как-повернуть-матрицу-двумерный-массив-на-90-градусов-с-помощью-zip
    i = 0
    j = 0
    (a,b) = np.shape(matrix)
    for i in range(a):
        for j in range(b):
                 if i == j:
                    matrix[i,j] = 0
                    # хз, как цикл убрать :((
    print(np.array(switched + matrix))


In [52]:
matrix = np.array([[1, 2, 3, 4], [0, 5, 6, 7], [0, 0, 8, 9], [0, 0, 0, 10]])
make_symmetric(matrix)

[[ 1  2  3  4]
 [ 2  5  6  7]
 [ 3  6  8  9]
 [ 4  7  9 10]]


### 9

Напишите функцию, создающую прямоугольную матрицу из m одинаковых строк, заполненных последовательными натуральными числами от a до b включительно в возрастающем порядке. Например, если m = 5, a = 3, b = 10, то на выходе будет матрица
$$
\begin{pmatrix}
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
3 & 4 & 5 & 6 & 7 & 8 & 9 & 10\\
\end{pmatrix}
$$

In [91]:
def construct_matrix(m, a, b):
    c = np.arange(a,b+1)
    print(c*np.ones((m, b - a + 1), dtype=np.int16))

In [92]:
m = 5
a = 3
b = 10
construct_matrix(m, a, b)

[[ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10]]


### 10

Напишите функцию, вычисляющую [косинусную близость](https://en.wikipedia.org/wiki/Cosine_similarity) двух векторов. Например, если на вход поступают вектора `array([-2, 1, 0, -5, 4, 3, -3])` и `array([0, 2, -2, 10, 6, 0, 0])`, ответом будет -0.25.

In [93]:
def cosine_similarity(vec1, vec2):
       # A*B/|A|*|B|
   #dot() сколярное произвдение https://pyprog.pro/linear_algebra_functions/dot.html
   #norm() векторная норма https://pyprog.pro/linear_algebra_functions/linalg_norm.html

   print(np.around(np.dot(vec1,vec2)/(np.linalg.norm(vec2)*np.linalg.norm(vec1)),decimals=2))


In [94]:
vec1 = np.array([-2, 1, 0, -5, 4, 3, -3])
vec2 = np.array([0, 2, -2, 10, 6, 0, 0])
cosine_similarity(vec1, vec2)

-0.25
